# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20160114_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_on',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AddField(
            model_name='product',
            name='price_recurring',
            field=django_prices.models.PriceField(currency='USD', decimal_places=2, max_digits=12, null=True, verbose_name='recurring price'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='hours', max_length=8, verbose_name='unit'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
