# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20160222_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='main_variant',
            field=models.BooleanField(default=False),
        ),
    ]
