# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20160114_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street_address_2',
        ),
        migrations.AddField(
            model_name='address',
            name='personal_number',
            field=models.CharField(default=11, max_length=12, verbose_name='personal number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(default='Sweden', max_length=2, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=20, verbose_name='postal code'),
        ),
    ]
